# Generated by Django 3.2.12 on 2022-05-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0002_rename_name_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_id',
        ),
    ]
