# Generated by Django 3.2.12 on 2022-07-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0003_remove_user_u_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_name',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fdoc', to='dbapp.doctor', verbose_name="Doctor's name"),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='p_name',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fpat', to='dbapp.patient', verbose_name="Patient's name"),
        ),
    ]
