# Generated by Django 3.2.12 on 2022-07-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbapp', '0004_auto_20220701_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('c_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('comp', models.TextField(max_length=1000)),
                ('doc', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cdoc', to='dbapp.doctor', verbose_name="Doctor's name")),
            ],
        ),
    ]
